site_name: Frankh

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: blue

nav:
  - Home: index.md
  - Watchfaces gallery: gallery.md

extra_css:
  - extra.css

plugins: []