site_name: Frankh
copyright: 'Copyright &copy; 2026 Frankh'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: blue

# Add this section right here:
extra:
  generator: false

markdown_extensions:
  - attr_list          # Allows adding CSS classes like {: .center}
  - md_in_html         # Allows Markdown syntax inside <div> tags
  - pymdownx.superfences # Better handling of nested blocks

nav:
  - Home: index.md
  - Watchfaces gallery: gallery.md

extra_css:
  - extra.css