site_name: Frankh
site_url: https://frankh93.github.io/
copyright: 'Copyright &copy; 2026 Frank Hernández'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: blue

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences

nav:
  - Home: index.md
  - Watchfaces gallery: gallery.md

extra_css:
  - extra.css